### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by Gnorme** [jimjimovich/caddy-stencil#1]
If I understand correctly, with this plugin you could serve a template file that's populated with json data from a proxied backend? Do you have any examples of how you use it?

**Comment by jimjimovich** [comment]
Yes, that is one of the things it would allow you to do. I'll try to get some examples up soon.

**Comment by jimjimovich** [comment]
I refactored things and all of the json examples should work now!

**Comment by Gnorme** [comment]
Awesome, thank you.

The json example displays the raw returned json rather than inserting it in to the template. Am I missing a step?

**Comment by Gnorme** [comment]
"Resource interpreted as Document but transferred with MIME type application/json" - is this the issue?

**Comment by jimjimovich** [comment]
In caddyhttp/httpserver/plugin.go, you need to add "stencil" between "templates" and "proxy".

**Comment by Gnorme** [comment]
Did that, still the same result

**Comment by jimjimovich** [comment]
Did you also add 
  _ "github.com/jimjimovich/caddy-stencil"
to caddy/caddy/caddymain/run.go ?

Does it show stencil in the list of plugins when you run caddy -plugins ?

**Comment by Gnorme** [comment]
Yes to both. The other examples run and work just fine, just the json one not working.

**Comment by jimjimovich** [comment]
Weird. I just built in from scratch in a fresh AWS Cloud9 environment and everything works.  I wonder if it has something to do with the fact that the example is relying on the template plugin as well.  That actually shouldn't be necessary at all, but I'm having a problem with some template methods not working as expected.

**Comment by jimjimovich** [comment]
I removed the template directive from the json example.

Also, do you have any other plugins installed or can you tell me any info about your environment? I'm not able to reproduce an error.

**Comment by Gnorme** [comment]
For this I was using a freshly built caddy with stencil as the only extra plugin.

go version go1.10.2 windows/amd64

Turns out maybe it's windows related? I decided to give it a try on my linux VM and now the json example is working just fine.

**Comment by jimjimovich** [comment]
My guess is that it has something to do with MIME types on Windows.  I made a change that should add the json mime type at plugin setup time. Could you possibly test that for me on Windows @Gnorme?

**Comment by Gnorme** [comment]
Sure thing. I'll let you know how it goes

**Comment by Gnorme** [comment]
Yup, that did it. Works just fine now :+1: 

Thanks!

**Comment by jimjimovich** [comment]
Great. Thanks for trying it out!
